apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement
  labels:
    app: usermanagement
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usermanagement
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:  # pod template
    metadata:
      labels: 
        app: usermanagement
    spec:
      containers:
        - name: usermanagement
          image: boming/usermanagement-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: usermanagement-cm
                  key: MONGO_URI
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: usermanagement-cm
                  key: MONGO_DATABASE
      
