apiVersion: v1
kind: Service
metadata:
  name: usermanagement-svc
  labels:
    app: usermanagement
spec:
  selector:
    app: usermanagement
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080