// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"usermanagement/internal/handlers"
	"usermanagement/internal/services"
)

// Injectors from wire.go:

func InitializeServer() (*handlers.Server, error) {
	userServiceInterface, err := services.NewUserService()
	if err != nil {
		return nil, err
	}
	server := handlers.NewServer(userServiceInterface)
	return server, nil
}
