// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"usermanagement/internal/handlers"
	"usermanagement/internal/services"
)

// Injectors from wire.go:

func InitializeServer() (*handlers.Server, error) {
	userService := services.NewUserService()
	server := handlers.NewServer(userService)
	return server, nil
}
